{
  "tests/login_test.py::test_forced_failure": true
}